### PR TITLE
Fix screenshot in Manual.md to reflect the current UI

### PR DESCRIPTION
**Pull request by user153**

### CODE REVIEW

**Comment by ctubio** [comment]
many thanks for your time'' i had skipped this for months cos i dont have enough skills/patience to edit images.

thanks again'¡

**Comment by user153** [comment]
glad to help, I enjoy tinkering with the bot, I was hoping I could  unlock all market levels...

**Comment by ctubio** [comment]
the address you wanna unlock is the one in the screenshot¿ or is another?

feel free to pasteit here nad i will unlock it

**Comment by user153** [comment]
the one in the screenshot is good.

**Pull request merged**
