### PR TITLE
Rename WHITE_R🐰BBIT to WHITE_RABBIT

### PR DESCRIPTION
**Pull request by b-seite**
Can we rename that file? It looks incredibly sweet but mit Git on OSX hates this filename and throws errors like that: fatal: pathspec 'WHITE_R\360\237\220\260BBIT' did not match any files

### CODE REVIEW

**Comment by ctubio** [comment]
can you please try `git config --global core.precomposeunicode true` before we kill the white r🐰bbit :dancer:

**Comment by b-seite** [comment]
sorry but that did not help.
still the same Error when trying to add to repository 

fatal: pathspec 'WHITE_R\360\237\220\260BBIT' did not match any files

my OSX is configured to german language

**Comment by ctubio** [comment]
aaand what about `git clone https://github.com/ctubio/Krypto-trading-bot -c core.precomposeunicode=true` ? ooor.. `git clone https://github.com/ctubio/Krypto-trading-bot -c core.quotepath=false` ? or `git config --global core .quotepath false` and then clone? :dancer: cos the error happened when running `git clone https://github.com/ctubio/Krypto-trading-bot' ?

i my osx the unicode chars in terminal apps using german or catalan languages works even better than on linux, can you please share yours versions?

**Comment by ctubio** [comment]
tenor 1

**Comment by b-seite** [comment]
Thaaanks a lot. 

this helped me: **git config --global core.quotepath false**

so the  Killer Rabbit of Caerbannog can stay alive

**Comment by b-seite** [comment]
ah i forgot something... here are my specs:

```
$ git --version
git version 2.13.5 (Apple Git-94)
$ uname -a
Darwin b-MBP.fritz.box 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
```

**Pull request closed without merging**
