### PR TITLE
Fixed UI bug placing sopSize and sopTrades labels/values

### PR DESCRIPTION
**Pull request by donaldforest**
Previously when you save settings data from field sopSize go to sopTradesMultiplier and sopTrades to sopSizeMultiplier. Labels has incorrect table titles but correct html hints. With this fix I check when add to Web UI this data:
sop = TradesSize
sopWidth = 1.1
sopTrades = 2.2
sopSize = 3.3
and check in DB f.json:
... "sopSizeMultiplier":3.3,"sopTradesMultiplier":2.2,"sopWidthMultiplier":1.1,"superTrades":3, ...

Attention! This fix can be not full according server side issues. On server side superTradesActive is a boolean var. As I see, in case when you choose another middle cases like sop = Trades and sop = Size you still continue work like for case sop = TradesSize. I not found in code checks for superTrades == 1, superTrades == 2 or superTrades == 3 (TradesSize).
I could be wrong, because I no experience with server side code, but if you review my investigation of server side code connected with sop and all will be true, it must be fixed. Simple fix is removing from UI middle sop options like sop = Trades and sop = Size and always using sop = TradesSize (Rename to On). In this case who will using sop = On it just need use unused Multipliers with 1 values. For example:
sop = On
sopWidth = 2
sopTrades = 2
sopSize = 1

Another fix is change logick of superTradesActive from boolean to int and review all cases in server code..

### CODE REVIEW

**Comment by b-seite** [comment]
hi @donaldforest 
thanks to find the errors. Think that i was the one who made them.

For server side: you can not find any checks for superTrades == 1 or similar because the values are not used as integer anymore. They are floating point values and you can choose values with decimals. they are simple multipliers to size and trades and these values are values with decimals possible.
if you have PingWith set to 5 and SopSize set to 1,5 then you get a resulting PingWidth of 7,5.
Or if you have trades set to 2 and SopTrades set to 1,2 then you get a resulting trades value of 2,4.

**Comment by ctubio** [comment]
so the server side is fine for you @b-seite ?

**Comment by donaldforest** [comment]
@b-seite No superTrades is integer value for select box un UI
0 - sop Off
1 - sop just Trades (or Size)
2 - sop just Size (or Trades)
3 - sop TradesSizes

**Comment by b-seite** [comment]
Ah now i know what you mean. `superTradesActive` is a variable that is in the code to signalize one subroutine (applyTradesPerMinute) that the super trades are on from another. The thing you are searching is this: `qp->superTrades == mSOP::Trades` or `qp->superTrades == mSOP::TradesSize` for example. That´s where we decide which function is activated. 

@ctubio for me the server side is fine.

**Comment by donaldforest** [comment]
@b-seite maybe. Again I still not familiar with server side. Sorry if confused you.
BTW next string is not hardcoded calculation of BBO? I mean in some case users can use wBBO..
if (!qp->buySizeMax) rawQuote->bid.size = fmin(qp->sopSizeMultiplier * buySize, (quoteAmount / ((MG*)market)->fairValue) / 2);

**Comment by b-seite** [comment]
@donaldforest  yes i am a bit confused...

the next line does not calculate the FV. It just uses the fairValue which is calculated here:
https://github.com/ctubio/Krypto-trading-bot/blob/6ed60c072ead2f98158c3a270f55a87ac05cfbd8/src/server/mg.h#L104-L121
respecting BBO or wBBO setting in the GUI (see line 113)

**Comment by donaldforest** [comment]
OK, thanks!
Sorry for false alarm about server side.

**Comment by b-seite** [comment]
no problem and again: thanks for finding the error

**Pull request merged**
