### PR TITLE
Tweaking manual

### PR DESCRIPTION
**Pull request by halessi**
Just adding a quick note on saving quoting parameters to the Manual as this is something I was confused about at the start.

### CODE REVIEW

**Comment by ctubio** [comment]
thank y ou for your time''


i agree with all you new text less than the note:
```
Note: This typically will need to be done when upgrading to the latest commit.
```

i think that is not true.
since upgrades does not remove the database, is not needed to save/restore nothing while upgrading.

**Comment by halessi** [comment]
Whoops, I will remo

> thank you for your time''
> 
> i agree with all you new text less than the note:
> 
> ```
> Note: This typically will need to be done when upgrading to the latest commit.
> ```
> 
> i think that is not true.
> since upgrades does not remove the database, is not needed to save/restore nothing while upgrading.
> 
> (in fact, databases are never removed, so is never expected for the parameters to be lost)
> 
> are you sure that you really need to save/restore configs after upgrade?

Whoops, I hadn't realized that databases aren't removed when upgrading. I'll take that part out.

**Comment by halessi** [comment]
Oops, didn't mean to close. Not sure if this counts for unlocking.... :)

**Comment by ctubio** [comment]
:koala: sure no problem

you are welcome''¡ :dancer:

**Pull request closed without merging**
