### PR TITLE
more precise EWMA recalculation

### LINKED ISSUE #523: EWMA_LS strange behaviour last time
Hello!

After changing pDiv settings I received this picture where EWMA Short and EWMA Long (Yellow) swapped places to opposite:
ewma

Interested behaviour of Yellow line (EWMA Long). On this image his value 300+ min. BTW its not first time, when I see similar behaviour for long and very long EWMA lines when i save changes. In previous cases I just add 1 to EWMA long value like 300 and then 301, and EWMA_L make some abnormal curvature.
+ In last releases I noticed big difference of EWMA's values in K if compare it with tradingview. I mean not concrete values (yes I know it can have different input data and calculations), I mean crossing ewma with same values. If on tradingview ewma's with same vales crossed, but on K charts in same time there is nothing like (i can be parallel and far)..

### PR DESCRIPTION
**Pull request by b-seite**
Hi Carles,

here is my attempt to recalculate the EWMA´s more precisely to resolve  #523. It is done by calculating the EWMA over the whole set of accumulated values, not only the last ones defined in the user settings. 

K also checks if a recalculation is needed and only recalculates if necessary.

Now it also recalculates even if there are less values available than the user setting. I think that even a calculation over some values is better than nothing.

what do you think?

### CODE REVIEW

**Comment by ctubio** [comment]
err.. just a comment, this conditions will always be false, no?
```
        unsigned int VLEP = qp->veryLongEwmaPeriods;
        if (VLEP != qp->veryLongEwmaPeriods) ....
```
i dont get it :D

**Comment by b-seite** [comment]
Hi Carles,
the as i understand static variables in functions right then the static variable is initialised once and can be reused every time the function is called. so 
`static unsigned int VLEP = qp->veryLongEwmaPeriods;`
will be done only once. That means 
if (VLEP != qp->veryLongEwmaPeriods) can be false the next time the function is called and when the quoting parameters changed.
maybe its not the best way but for me it worked. 
I´ll have a look at it and see if i can program it a bit more clear

**Comment by ctubio** [comment]
you are totally right, i just want to point that after the condition validates as true (because user updated QP), then forever will be true cos VLEP is set on boot and may or may not be equal to whatever the user saves, but if is not equal, it will be forever not equal, not just the first time is validated.

**Comment by ctubio** [comment]
many thanks for your super fixes, anytime you consider is done please leave a comment and i will jump into :dancer:

**Comment by b-seite** [comment]
Hi Carles,
for me it works it as it should now.  
I added the amount of values that are used for the calculation to the cli output. Maybe it helps someone to find some more mistakes made by me...

**Comment by ctubio** [comment]
quite difficult since your codes are awesome! xD ok thanks will merge soOn''

**Pull request merged**
