### PR TITLE
Fixes for wallet size limits.

### PR DESCRIPTION
**Pull request by xloem**
This is a squash, rebase, and fixup for #919.

- account for maker fee at all steps
- don't attempt to spend held balances ('total' becomes 'amount')
- remove some redundant checks and truncations

### CODE REVIEW

**Comment by ctubio** [comment]
just saying, takeFee was not wrongly used instead of makeFee, that was because hitbtc and beqaunt are silly; ima rereview thiz under hitbtc/bequant

:koala: many thanks for your time'''

**Comment by xloem** [comment]
I kind of see; I misinterpreted the reason for that line.

It seems to me that hitbtc/bequant could do some of that adjustment inside the gw code, and provide a makeFee that includes their takeFee ...  but really sounds a hard situation =S

The code I added was to make sure that sizes include the makeFee for coinbase, since they e-mailed to complain I wasn't including fees in orders =S

**Comment by ctubio** [comment]
i think thiz is wrong:
```
wallet.base.amount / (1.0 + K.gateway->makeFee)
```
instead should be:
```
wallet.base.amount * (1.0 - K.gateway->makeFee)
```

**Comment by xloem** [comment]
@ctubio

what's behind your math?

Here's mine:

- The amount we have available to sell is `wallet.base.amount`
- The amount we plan to sell is `wallet.ask.size`
- The amount we will actually lose if we sell `wallet.ask.size` is:
  `wallet.ask.size * (1.0 + K.gateway->makeFee)`
  That's the amount we sell plus the fee.

So, we can write an equation about the most we can possibly sell:

    quotes.ask.size * (1.0 + K.gateway->makeFee) = wallet.base.amount

If we solve for quotes.ask.size, we get:

    quotes.ask.size = wallet.base.amount / (1.0 + K.gateway->makeFee)

**Comment by ctubio** [comment]
quick link to related issue: https://github.com/ctubio/Krypto-trading-bot/issues/926

**Comment by ctubio** [comment]
many thanks for shrink the operations and conditions and include fees'¡

**Pull request merged**
