### PR TITLE
Recalc Ewma from historical values

### LINKED ISSUE #439: 💾 💾  Improvement: saving history of price for fast ewma recalculation 💾 💾
Hi Carles and all,

The idea is just to save in the DB the FV every minute during a period of time that we can define in the UI.

The goal is to be able to calculate ewma from there in case we change settings (instead of waiting for a long time).

One example:
So let's say I tell the bot to keep the 2000 past minutes FV and I'm using ewma 200/100.
Then I change my mind and I want to use 1000/500, with the current form, when I change the setting, I have to wait 1000 minutes before the bot is up to date with the correct ewma.

However, if it keeps in the db the FV of the past 2000 minutes, it takes only a few milliseconds for the bot to recalculate the correct ewma from the db. (just need to do the formula 1000 times and 500 times respectively).

I think that's a great plus for everyone that like to try and change their settings from time to time, and of course, if you don't want to use it, just set in the UI 0 and it will not save any data.

What do you think ? 😄 

Best,

Camille

### PR DESCRIPTION
**Pull request by b-seite**
Hi Carles, 

finally i got it (i hope) to resolve #439 
This one stores FairValues in a separate DB every Minute (because i found no DB what does this)
It deletes Values older than 24h from the DB.
On `Save` in the GUI it recalculates the four EWMA´s from the data  and displays the new values the command line.
I Hope that the calculation is correct. Everybody please check and check twice. 
there are some CLI log infos that we can remove if we are sure that it works correctly.

### CODE REVIEW

**Comment by b-seite** [comment]
Ah Carles,
one issue that took me hours to find: When a DB still exist with a lowercase letter i.E. `e` then you can not add a new DB with a capital letter `E`. K writes the data to the existent DB `e`
That's the reason why i chosed `G` because the next free letter did not work. maybe we fix that sometimes... But in any case good to know and not forget

**Comment by ctubio** [comment]
yea hope this helps (for example):
```
sqlite3 --cmd ".quit" /data/db/K.3.BTC.EUR.db "SELECT * FROM e;"
sqlite3 --cmd ".quit" /data/db/K.3.BTC.EUR.db "SELECT * FROM E;"
```

**Comment by ctubio** [comment]
many thanks for your time'' will review soOn'' :dancer:

**Comment by ctubio** [comment]
awesome codes many thanks'¡

**Comment by Camille92** [comment]
Hi guys thank you for your work!

I just have a request, with ewma_4 my long and very long ewma are way over 24h, would that be possible to change the 24h for something else?

(or let to the appreciation of the user?)


Best,

Camille

**Comment by b-seite** [comment]
Yes for sure. I suggest 96h then? 
That are 5760 stored Values max. 
@ctubio then we have to re-rename the variables from fairValue24h to fairValue96h 
Will do that later this day.

**Comment by Camille92** [comment]
It sounds good to me :)

**Comment by ctubio** [comment]
thanks again for your time, i will do this little mod of 96h laterz'

**Pull request merged**
