### PR TITLE
Mobile lightweight separate version of web UI

### PR DESCRIPTION
**Pull request by donaldforest**
**TODO:**
- Cleanup heavy js libs (if there are such, already removed some..)
- Simple buy\sell report
- Automatically switch to mobile version according Browser Useragent (save layout to cookie)
- Indicator of free version

**WARNING:** Need detailed test and review of "Makefile" and "ui.h" (server side commit). Someone who most familiar with server side code.

k_mobile

### CODE REVIEW

**Comment by serzhiio** [comment]
Wow, looks great!

**Comment by donaldforest** [comment]
@serzhiio Any suggestions add something or remove are welcome..

**Comment by ctubio** [comment]
many thanks for you time''

lemme try to not duplicate all the logic and will merge when done

thanks again'¡

**Comment by donaldforest** [comment]
@ctubio Sure! Thanks! But duplication directed to create page which not load some additional modules which not used in mobile version like charts and tables.. Yes will be so better create 1 same adaptive UI face for mobiles and desktop devices, but ... is to scary like for me (in this case we can touch some important UI details, lowering backward compatibility)! Then I try go this way with 2 independent faces which loads independent amount of modules and elements as it possible.

**Pull request closed without merging**
