### PR TITLE
fix #1015 

### LINKED ISSUE #1015: Web UI Disconnecting Constantly (Cannot read property 'ewmaWidth' of undefined)
Using latest Chrome and the web UI constantly displays for a brief moment and disappears immediately showing ~.sh is disconnected screen.
If I leave the UI open for long enough it will randomly connect.
Restarting K doesn't seem to fix it either.
Running latest commit with fully updated debian buster.

Edit: Seeing this in my console log on Brave.
client.min.js:1 ERROR TypeError: Cannot read property 'ewmaWidth' of undefined
    at StatsComponent.updateCharts (client.min.js:1)
    at client.min.js:1
    at ZoneDelegate.invokeTask (client.min.js:1)
    at Object.onInvokeTask (client.min.js:1)
    at ZoneDelegate.invokeTask (client.min.js:1)
    at Zone.runTask (client.min.js:1)
    at ZoneTask.invokeTask (client.min.js:1)
    at ZoneTask.invoke (client.min.js:1)
    at timer (client.min.js:1)
defaultErrorLogger @ client.min.js:1

### PR DESCRIPTION
**Pull request by jbransom**
Fix: updateCharts to check for ewma before checking property.

### CODE REVIEW

**Comment by ctubio** [comment]
excuse me for taking so long; will be merged asap; thank you for your time'''

**Comment by jbransom** [comment]
Looks like I left out the btc address for the commit when reformatted the description. 
The native segwit address is : bc1qwu5sm3ev043ywrfjp9hxa075l27ze9nap5lmlu
Thanks!

**Comment by ctubio** [comment]
er... from where comes this address? i am not using Bech32 to generate the btc addresses for this bot

for sure i started with P2PKH and by now im (still) using P2SH; are you sure you dont have any address starting with a `1` or a `3`? (cos thats the only address formats i had ever generated)

**Comment by jbransom** [comment]
I didn't generate the address with the bot. This is an existing segwit wallet: 
3DnkW21pizun29ETbYRok47YXT11FvEWoG

Is it a requirement to generate the wallet with the bot?

**Comment by ctubio** [comment]
i am bit confused of what are you trying to do.

3DnkW21pizun29ETbYRok47YXT11FvEWoG is not a btc addr associated with any bot, so i canot unlock any bot using  3DnkW21pizun29ETbYRok47YXT11FvEWoG

i usualy unlock a bot after a PR; unlocking a bot means that each bot has a unique btc addr associated; you cannot create your own

a give btc addr of a bot is like a license key that can be unlocked; other btc addr in the network (or from other bots) has no meaning; to unlock it i can do it without doing any transaction in the network after aproving a PR or otherwise users can pay the price of the bot anonymously anytime

the btc addr of each locked bot is displayed on exit in the terminal and permanently in the frontend, is generated on first run and remains the same forever

hope this helps''

**Pull request merged**
