### PR TITLE
Web UI Updates.

### PR DESCRIPTION
**Pull request by nithi2023**
Hi!
I have made some UI improvements! please review and let me know your opinion :) 

Here are the notable changes made:
* Quoting Parameter input area UI improved.
* Safety & Quoting parameters display area improved.
* Consistancy of fonts, font-sizes, colors.
* Button outlines removed, unused classes removed from .ts files.
* All these changes applied to both dark, and light version.

Here is how it looks [Dark UI](https://imgur.com/a/9XwElK8) & [light UI](https://imgur.com/OiRdeAP).

### CODE REVIEW

**Comment by nithi2023** [comment]
@ctubio Can you please let me know what to do next. codacy code analysis showing up issues.

**Comment by ctubio** [comment]
:bulb: sorry for codacy, i just have it for historical reasons (and cos i hope for it to be usefull some day)

:koala: but but but pvs-studio turned to be much much better, so maaaybe codacy will be removed someday

**Comment by ctubio** [comment]
:woman_dancing: awesome mods'¡ thank you for your time''''

let me just increase some heights to avoid some empty spaces (trades and stats) and see how we can reduce a bit the height of the page, cos i would like to avoid vertical scroll for everybody while having less than 768px of height in total

it hurts my eyes the non-linearized safety stats but it makes lot of sense to have it porperly aligned so let me see how can i adapt myself to it without touching your great work

:koala: if you agree please let me know the BTC address of the bot that you wish me to unlock for you cos this will be merged with little mods soon sure.

**Comment by nithi2023** [comment]
Thanks @ctubio for fixing my codes with proper heights :) 
Hope you adapt to new safety stats look!

Here is my BTC address: `33LiwrdKNkmVQyi2Q53hTfRM6z3pnfdogH`
Thanks for unlocking!!

Also, Let me know if any improvement points you have with UI.

**Comment by eniware-org** [comment]
Looks really good!
As a suggestion, can you enable the copy cells operation on the grid? Export to CSV will be even better!

**Comment by nithi2023** [comment]
Hi @ctubio, I have just lost my API Secret for the key which I used for unlocking, would you mind If I ask another. You can block previous? Thanks

**Comment by nithi2023** [comment]
> Hi @ctubio, I have just lost my API Secret for the key which I used for unlocking, would you mind If I ask another. You can block previous? Thanks Previous API Key: cuDFIPk8bghZObbZ6le58IY05fWvkogEyoloDMSVQLAmu3JlhnVqLnS04lFBLapF New API Key: 7ro2SgRybKSVNJhWUkR6tJDWaTxxqUXKZRdvfOZHI2l8TJKIBjLmZbxV9LZgC0TY

@ctubio please.

**Pull request merged**
