### PR TITLE
Fix wrong EWMA recalculation

### LINKED ISSUE #474: Error in the calculation of ewma after a "save"
Hello everyone,

I realized that when you save new values in your settings, the ewma are not calculated properly during 1mn.

I guess there's something to do with new ewma recalculation here, but I can't say for sure.

Here is one example of what you get in stats.

The problem is that it changes your TBP to 0 during 1mn.

I'm using EWMA_4 and the problem is only with medium and short.

capture d ecran 2017-12-13 a 22 22 40

### PR DESCRIPTION
**Pull request by b-seite**
Hope that it helps to resolve #474 

btw. i have seen that the recalculation routine recalls only if there are enough values available. My attempt was to use the very last available value for the missing ones... won't we give that a try?

### CODE REVIEW

**Comment by ctubio** [comment]
but calculating ewmas based on fake equal values will give a 0 variation ewma during that periods

**Comment by ctubio** [comment]
also im sorry but are you sure this PR makes any difference?

**Comment by b-seite** [comment]
yes you're right. The problem is vector::end.
It points past the end so the last calculation is done with a value of 0

**Comment by ctubio** [comment]
ima get rid of the end(), thanks for notice the overflow'¡

**Pull request merged**
