### PR TITLE
TakeProfit test

### PR DESCRIPTION
**Pull request by woshikie**
Hi, i'd like to implement #58 but I don't have enough funds to test, nor do I have the unlocked bot to test with my minimum funds

### CODE REVIEW

**Comment by serzhiio** [comment]
Could you describe the logic you propose for take profit?

**Comment by woshikie** [comment]
im basically following this comment here
image

**Comment by ctubio** [comment]
thanks for your time''' will review soOn''

im not very fan of this but will do my best to happily understand it

**Comment by woshikie** [comment]
Im pretty sure this isn't going to be the last PR for to implement this feature, but a starting point instead. I certainly need points as to where the web UI gets all the strategies and how to add an input to the UI and link it back to the engine

**Comment by ctubio** [comment]
thanks ok no worry i will implement the UI code if finally the server code is nice

**Comment by woshikie** [comment]
actually, i kinda did this for the unlock opportunity. So, I also hope to get my bot unlocked :P

**Comment by ctubio** [comment]
my hopes are also into not having PR opened for days and to not invest time understanding it just to close it; an acceptable PR satisfy yours and my hopes at once. don't stop yourself if you think you can provide more commits to enhance the new version  you are going to unlock

**Pull request closed without merging**
