### PR TITLE
Dynamic Market Width Calculation

### PR DESCRIPTION
**Pull request by b-seite**
Hi Carles,

here is my suggestion for the request of a ewma market width function. It was demanded several times the last months so i thought it´s a good idea to give it another chance.

What it does:

- every time the FV is recalculated, it also calculates a linear average of the market width. (with gdax i get 30-120 values for the average every minute)

- every minute it calculates a ewma from the average built above and resets the linear average 

-  the number of ewma values is taken from the ewmaPeriods setting, so it has only one  additional checkbox in the configuration.

- the number of code lines and the complexity is as low as possible. No more vector and (at the moment) nothing to store in the db.

what you think, is it worth to add the description in the manual?  
Ah yes, and of course, the one line with the debug info can be removed.
boris

### CODE REVIEW

**Comment by ctubio** [comment]
many thanks for your time, will happily review soOn'

**Comment by ctubio** [comment]
just to be clear, this is related to https://github.com/ctubio/Krypto-trading-bot/issues/328 ?

**Comment by b-seite** [comment]
Yes thats right ( if i understood it right in #328 )

**Comment by ctubio** [comment]
awesome codes'' many thanks for your time will merge in the next tar build

**Comment by ctubio** [comment]
finally thanks to this stats.ts will be aware of quoting parameters :D so in next commits ima try to make stats react against quoting parameters and only show what is really enabled :D

**Comment by ctubio** [comment]
i will update the manual tonight; thanks again'¡

**Pull request merged**
