### PR TITLE
fix class GwPoloniex  http url

### PR DESCRIPTION
**Pull request by ccc030233**
fix class GwPoloniex: public GwApiWs  >>>>> "https://api.poloniex.com";   "wss://ws.poloniex.com";

### CODE REVIEW

**Comment by ctubio** [comment]
:koala: thank you alot'¡

**Comment by ccc030233** [comment]
in  [Unlock](https://github.com/ctubio/Krypto-trading-bot#unlock) section   
" the BTC Payment Address for the bot that you wish ..."  should i put my btc Address here for Unlock ?

**Comment by ctubio** [comment]
yes please, here is ok, or in any other channel you preffer, thank you'¡!

**Comment by ccc030233** [comment]
thank you ,  btc:
3L6nvo66C1zEE9uTipD4BAdMrD41EWFeHc

**Comment by ctubio** [comment]
3L6nvo66C1zEE9uTipD4BAdMrD41EWFeHc is now unlocked

**Pull request merged**
