### PR TITLE
Report Losses from Trades

### PR DESCRIPTION
**Pull request by xloem**
This patch adds a test for a scenario in which I saw corruption, and fixes the immediate cause of the corruption by properly reporting pongs that lose money rather than making it.

### CODE REVIEW

**Comment by ctubio** [comment]
awesome test; is the first that uses gw (not even HelloWorld uses gw yet)

will review soOn''' many thanks for your fix + testunit'¡!

**Comment by xloem** [comment]
i'm kind of new to tests, not sure if I laid it out right.

it seems the other tests in that file use Gw.  I didn't think of HelloWorld as being a test, guess I didn't think much of it.

**Comment by ctubio** [comment]
let me rethink this, cos trading-bot effectively cannot do a pong with losses (a pong with losses is not matched, instead it becomes a new ping in the history)

**Comment by xloem** [comment]
there is some other underlying bug -- my system is sometimes matching trades wrongly.  when such a bug happens, it is highly helpful to have the history consistent and make the user aware.

what do you think of including 35a6b68 with a comment that it indicates a bug if it ever happens?

**Comment by ctubio** [comment]
ok, lets fix the bug in the history in case that is somehow possible by other bots/codes to reach this situation; will merge soOn; many thanks''

**Comment by xloem** [comment]
> let me rethink this, cos trading-bot effectively cannot do a pong with losses (a pong with losses is not matched, instead it becomes a new ping in the history)
> 
> see:
> [Krypto-trading-bot/src/lib/Krypto.ninja-data.h](https://github.com/ctubio/Krypto-trading-bot/blob/f9d65ebe2972afc92dba64a8349705f32b7ff3bd/src/lib/Krypto.ninja-data.h#L2315)
> 
> Line 2315 in [f9d65eb](/ctubio/Krypto-trading-bot/commit/f9d65ebe2972afc92dba64a8349705f32b7ff3bd)
> 
>  quotes.ask.isPong = quotes.ask.price >= wallet.safety.buyPing + widthPong; 
> 
> and:
> [Krypto-trading-bot/src/lib/Krypto.ninja-data.h](https://github.com/ctubio/Krypto-trading-bot/blob/f9d65ebe2972afc92dba64a8349705f32b7ff3bd/src/lib/Krypto.ninja-data.h#L2326)
> 
> Line 2326 in [f9d65eb](/ctubio/Krypto-trading-bot/commit/f9d65ebe2972afc92dba64a8349705f32b7ff3bd)
> 
>  quotes.bid.isPong = quotes.bid.price <= wallet.safety.sellPing - widthPong; 
> i mean, isPong is not randomly defined, is a consequence of the relation between the current order price and the safety (last trade or last trade + protections) +/- widthPong

@cutbio, it looks like order matching and calculation of Kdiff is done without regard to the value of isPong, see https://github.com/ctubio/Krypto-trading-bot/blob/f9d65ebe2972afc92dba64a8349705f32b7ff3bd/src/lib/Krypto.ninja-data.h#L1280 . Do I have the meaning of "pong" wrong?

**Comment by ctubio** [comment]
because you are setting randomly `isPong` to `true` or `false`.

instead, what the app does at runtime, is set `isPong` to `false` by default, and only set it to `true` is there are pongs in the history to be matched with a positive Kdiff.

once the trade is filled, the pong matches cos there was a match before.

but you are setting `isPong` to `true` even when no matches exists in the history

that is a impossible situation for the bot, but a legit test if you ask me

**Comment by xloem** [comment]
@ctubio That makes sense, but the test is a snapshot from an actual bot run that produced the negative Kdiff.  After using the code that reports negative Kdiffs, I am seeing more of them in the interface when running bots.  It doesn’t look to me like the code actually uses isPong to decide whether to make matches or not — could you point out to me where this is done?  I’m using Boomerang mode as in the test.

**Comment by ctubio** [comment]
well i can't merge it today, hope for it tomorrow''' (cos https://twitter.com/dhstatus/status/1113192174168924160)

about your question, at the time of placing an order (quote creation) we do this calculation:
https://github.com/ctubio/Krypto-trading-bot/blob/f9d65ebe2972afc92dba64a8349705f32b7ff3bd/src/lib/Krypto.ninja-data.h#L2315
and:
https://github.com/ctubio/Krypto-trading-bot/blob/f9d65ebe2972afc92dba64a8349705f32b7ff3bd/src/lib/Krypto.ninja-data.h#L2326

then, when a trade is filled, that is in whatever time in the future (where the history may be or may not be the same) we do not trust the past, but instead calculate it again at:
https://github.com/ctubio/Krypto-trading-bot/blob/3baedebb7a6a14b8b02d73d777b293d0e78c77ff/src/lib/Krypto.ninja-data.h#L1292-L1294
^this condition happen inside a `else` statement that is only accessible by Boomeran/AK47, it walks over all history of trades, and tries to find the matching ping for the recently filled pong

in case it finds one, we cross fingers hopping that is the same that created the quote (otherwise nobody cares, thats why we just cross fingers [nobody cares cos the history is what it is; if is not what you expected while creating the quote may be cos another tradre matched in between; or whatever; that doesnt matter as of now), and just set K* values for ping (to make it become a pong), at: https://github.com/ctubio/Krypto-trading-bot/blob/3baedebb7a6a14b8b02d73d777b293d0e78c77ff/src/lib/Krypto.ninja-data.h#L1362-L1365

in the other hand in case that it doesnt finds one or in case that the filled quantity is still higher than what we have mached in history, it just creates a new ping with the remaining quantity, at (just below the lines pasted above follows):
https://github.com/ctubio/Krypto-trading-bot/blob/3baedebb7a6a14b8b02d73d777b293d0e78c77ff/src/lib/Krypto.ninja-data.h#L1366

the ping and the pong relationship inside the same object  (and all code related to matchPong() family of funcs) may be confusing; im sorry im not happy with it neither :P (as a note, K* values like Kdiff or Kval are related to the `pong` and without K prefix are related to the `ping`) but hey, this prefix is the first form of the app name, when it was still a pull request of tribeca xD

**Comment by ctubio** [comment]
i didnt know you where using a real log, thats why i said "randomly"; im sorry thanks for the clarification'¡

**Comment by ctubio** [comment]
btw, i would only trust real logs if history of trades is fully printed as a debug line before and after the debug msg of a filled trade :D (if you ask me)

**Comment by xloem** [comment]
ctubio, thanks for so much explanation.  I'm still finding time to process all the things you're saying.

> then, when a trade is filled, that is in whatever time in the future (where the history may be or may not be the same) we do not trust the past IsPong value, but instead calculate it again at:
> [Krypto-trading-bot/src/lib/Krypto.ninja-data.h](https://github.com/ctubio/Krypto-trading-bot/blob/3baedebb7a6a14b8b02d73d777b293d0e78c77ff/src/lib/Krypto.ninja-data.h#L1292-L1294)
> 
> Lines 1292 to 1294 in [3baedeb](/ctubio/Krypto-trading-bot/commit/3baedebb7a6a14b8b02d73d777b293d0e78c77ff)
> 
>  or (filled.side == Side::Bid 
>    ? (it.price > filled.price + widthPong) 
>    : (it.price < filled.price - widthPong) 
> 
> ^this condition happen inside a `else` statement that is only accessible by Boomeran/AK47, it walks over all history of trades, and tries to find the matching ping for the recently filled pong

To clarify, my test doesn't hit that line.  It ignores the price when deciding to become a pong because pongAt is set to AveragePingFair, I believe ( https://github.com/ctubio/Krypto-trading-bot/blob/3baedebb7a6a14b8b02d73d777b293d0e78c77ff/src/lib/Krypto.ninja-data.h#L1290 ).  This is why the Kdiff value ends up being negative.  Do you know if it is intended behavior to ignore the price for AveragePingFair and AveragePingAggressive?

**Comment by ctubio** [comment]
morning'''
AveragePingFair (as well as AveragePingAggressive) are OR conditions before the price condition, so if are set, all trades in the history are possible to be matched.

in case AveragePingFair (or AveragePingAggressive)  is not set, then trades are only matched if the prices match:

https://github.com/ctubio/Krypto-trading-bot/blob/3baedebb7a6a14b8b02d73d777b293d0e78c77ff/src/lib/Krypto.ninja-data.h#L1290-L1295

im not sure that i am understanding your issue, to me looks normal (expected) yea :S

**Comment by xloem** [comment]
It sounds like it's correct behavior, and 843b7063b5c81be301209f60a433776a6b4a390d should be integrated.  When all trades in history are possible to be matched, sometimes it picks prices that are actually losses instead of profits when paired.  This is tracked wrongly unless Kdiff can be negative.

**Comment by ctubio** [comment]
i will merge ina bit; totally agree, and even if i dont that situation may be possible so lets control it'¡ (better to have correct Kdiff than always possitive values with abs())

many thanks for your time'¡

**Comment by ctubio** [comment]
BUT if negative values are displayed, then means the trading codes are wrongly loosing coins (and a call to your favorite developer is needed xD)

**Comment by ctubio** [comment]
:koala: just creating a ref directly to this PR from the issue page: https://github.com/ctubio/Krypto-trading-bot/issues/909

**Comment by xloem** [comment]
> BUT if negative values are displayed, then means the trading codes are wrongly loosing coins (and a call to your favorite developer is needed xD)

I was trying to get my code to trade very frequently regardless of price in order to test the local wallet code I wrote.  I think the problem happened because the price changed _way_ more than the pingWidth, in the unprofitable direction.  So _any_ trades that were closed after that were losses.  The current code matches them anyway.

**Comment by ctubio** [comment]
just saying, somehow im not able to successfully run the new test, cos it says:
```
K/src/lib/../../test/units.h:472: FAILED:
  REQUIRE( trade.Kdiff > 0 )
with expansion:
  -0.002823096 > 0
```
let me zZzzzz and i loOk at it ina fresh new day

**Comment by xloem** [comment]
Hey, that test is supposed to fail.  I pushed it to demonstrate that the code presently generates negative Kdiffs to contribute to our discussion (I think I expected it to fail on travis to aid the point I made, but for some reason travis didn't run it).

That failing test line makes the test more strict by asserting that the backend not generate negative Kdiffs (call to favorite developer as you say) at any point in the test.  The test data was taken from a real-world run and is intended to represent a real-world condition, but it presently generates a negative Kdiff.

Do you care how it is handled?  Could just comment out the line ... would be best to decide whether the negative Kdiffs are a bug or not and fix it if it is, I suppose.  Simplest fix would be removing those `or` conditions that skip price checking.

**Comment by ctubio** [comment]
iSee, thanks for the explanation''

**Comment by xloem** [comment]
@ctubio, I've removed the commit that exposes that bug, so that this PR can be merged now without breaking the testsuite.  The full set of commits is still available at https://github.com/xloem/Krypto-trading-bot/tree/crosspongs-plusbug .

**Comment by ctubio** [comment]
:koala: many thanks for your time''' mergin'¡0

**Comment by xloem** [comment]
@ctubio , I'm still slowly thinking about and working on these things.  You said,

> AveragePingFair (as well as AveragePingAggressive) are OR conditions before the price condition, so if are set, all trades in the history are possible to be matched.
> 
> in case AveragePingFair (or AveragePingAggressive) is not set, then trades are only matched if the prices match:
> 
> https://github.com/ctubio/Krypto-trading-bot/blob/3baedebb7a6a14b8b02d73d777b293d0e78c77ff/src/lib/Krypto.ninja-data.h#L1290-L1295
> 
> im not sure that i am understanding your issue, to me looks normal (expected) yea :S

Could you clarify, maybe again, _why_ the price is ignored if AveragePing is set?  This allows unprofitable matches when the price has large swings.  It seems to me these OR conditions should be removed so that negative kdiffs do not show up.

**Comment by ctubio** [comment]
mm.. note that matchPong() functions are not yet executed when conditionaly testing AveragePing

AveragePing conditions just add items for later feed matchPong()

matchPong() is really who decides if a pong is a pong, so AveragePing is just defining an initial possible set of pongs, that still needs to be confirmed by matchPong()

thats why AveragePing can include pongs that are not finally matched pongs

hope that is what you mean''

**Pull request merged**
