### PR TITLE
[Feature] Auto EWMA Ping Width + Auto Pong Width

### PR DESCRIPTION
**Pull request by serzhiio**
Hi guys, hope it can help us all :)

### CODE REVIEW

**Comment by serzhiio** [comment]
Calculations of ewma market width are realtime. So choose period considering it.
Auto pong is calculated respecting current ewma market width that not less then minimum width.

**Comment by ctubio** [comment]
we already had ewma in realtime and moved it to each 1minute, market width is defined by stdev, and stdev already modifies the width in a predictable manner, why you need another ewma average to track the market width? it also have factor and all the fancy periods to make it fully customizable; it also runs every second, it also is based on topBid/Ask; and duplicating calcEwma is not nice :S

**Comment by serzhiio** [comment]
Cannot agree with your arguments.
The main idea is to control pingWidth automatically and not let it be very small in moment of high volatility especially when it comes big very quickly. IMHO 1s refresh rate is bad for momentum values like marketWidth. If STDEV works so predictable we should never have to manually change pingWidth. Think we should have a try to test it and can remove it anytime. Dont you think so?

**Comment by ctubio** [comment]
maybeee is possible without having another ewma variable? also maybe is possible to hardcode factor or the other parameter that is not a boolean? (just to reduce complexity? or for you are really really needed to be configurable?)

**Pull request closed without merging**
