### PR TITLE
prevent APR-adjusted orders from crossing the market

### PR DESCRIPTION
**Pull request by xloem**
Sometimes my buys or sells are just _empty_ with no explanation.

I passed --debug and found that APR was pricing pongs on the wrong side of the market when it had moved more than pongwidth since a ping.

Patch attempts to fix this so such pongs are placed.

EDIT: I've set the limit properly now.  It's as tight as possible without allowing for crossing.

### CODE REVIEW

**Comment by ctubio** [comment]
it makes sense the protection but maybe is too much?

what you think if we replace:
```
quotes.ask.price = max(levels.bids.at(0).price + K.gateway->minTick, wallet.safety.buyPing + widthPong);
```
by just:
```
quotes.ask.price = max(levels.bids.at(0).price, wallet.safety.buyPing + widthPong);
```
(without the `minTick` operation; and same for asks)

this way is still possible to place orders at the first level, nope?

(im not understanding the `minTick` operation only; but i think i get what youre trying to avoid even if i never experiencied it [im not sure why i didnt :S] so will merge soOn'')

**Comment by fuzzyTew** [comment]
@ctubio, it's actually comparing the *ask* price to the *bid* levels.  So it is supposed to be possible not only to place orders at the first level, but also beyond the first level.

If the lowest ask is 100.08, and the highest bid is 100.03, then a faulty ask for 99.98 will get raised to 100.04 .  That's

    quotes.*ask*.price = max(levels.*bids*.at(0).price + K.gateway->minTick, wallet.safety.buyPing + widthPong);

i.e.

    100.04 = max(100.03 + 0.01, 99.98)

Do I have that right or have I made a mistake?

I'm okay with whatever solution you pick, but it looks to me like the solution you proposed might not quite fix the issue because 99.;98 would go to 100.03, which is still a bid price, not an ask price.

**Comment by ctubio** [comment]
ah oh iSee, is bids against asks okok sorry to itz to late here :D will rereview and test and merge tomorrow''

:koala: many thanks for your time'''

**Comment by ctubio** [comment]
now, thats aggressive position rebalancing xDD

**Pull request merged**
