### PR TITLE
Add Docker Compose with SSL enabled integrated with NGINX proxy and autorenew LetsEncrypt certificates

### PR DESCRIPTION
**Pull request by kojojacob**
Hello friends and non-friends,
this pull request adds support for docker compose and helps using the Krypto-trading-bot behind a NGINX proxy with SSL Encryption and autorenew LetsEncrypt certificates.
It makes it more easy to the deploy a new instance of the bot very fast.

Can you please provide me some information about the probability of using a separate docker container for the management of the database. Is it somehow possible? 

And I activated the removing of the ssl certs in the Dockerfile because someone could have the idea to use the already generated certificate with published private key.

If you have any questions don't hesitate to ask.

Greetings Kojo Jacob

### CODE REVIEW

**Comment by ctubio** [comment]
im happy you noticed and reported the private key published, i had been waited 3 years for it xDD

pls let me send you a big thank you for collaborate into random projects with security enhancements'''' - thats what this world needs!

about the database, please note is a SQLite server-less database, so no need a second computer for a server-less service; the application just creates a file where the database is saved and updated, it does not talk to any SQL server.

since you didnt deleted or modified any current file, let me merge it as-is and i will test it later on master :D (while reading you awesome docs thanks'¡)

many thanks for your time''''

**Comment by ctubio** [comment]
just saying, i think nginx is not needed (and your docker installation seems too complex when can be done just with 1 Dockerfile); anyway i will keep it i think cos you are nto the first that suggest a docker-composer setup instead of a single Dockerfile

**Comment by ctubio** [comment]
btw..
```
 $ git clone https://github.com/ctubio/Krypto-trading-bot/tree/master/etc/docker-compose
Cloning into 'docker-compose'...
fatal: repository 'https://github.com/ctubio/Krypto-trading-bot/tree/master/etc/docker-compose/' not found
```

**Comment by kojojacob** [comment]
Hey,
sorry for the late reply, but I am on my way to Togo.

I throught I could copy only the folder with the config files.
Instead we should us these commands:

 $ git clone https://github.com/ctubio/Krypto-trading-bot
<https://github.com/ctubio/Krypto-trading-bot/tree/master/etc/docker-compose>.git

 $ cd etc/docket-compose/

I will write a pull request next week.
Thank you

**Pull request merged**
