### PR TITLE
Dynamic Position Divergence

### PR DESCRIPTION
**Pull request by b-seite**
Adds the ability to dynamically changes the pDiv according to the divergence from 50% of Value.
The Intention is to adjust the pDiv when the Market moves.
There are some computation modes available (linear, sine, square root and switch mode)
There is also a new pDivMin setting available. 
The bot calculates the pDiv dynamically between pDiv and pDivMin according to the distance from the center of the base value. The larger the distance the more it goes to pDivMin.

### CODE REVIEW

**Comment by ctubio** [comment]
very nice codes :D lemme test it :D

**Comment by b-seite** [comment]
Hej Carles,

soemthing new from me. it has to be tested heavily but i think its a quiet interesting feature. Thats what i wished to have in the last hurly-burly days. I got the idea from #6 but the solution is a bit different.

**Comment by Camille92** [comment]
Hey @b-seite , it looks very cool but so far I don't understand what are the factors that make pdiv to change. 
Can you please develop a bit on that??

Anyway, it's something that was really needed!

**Comment by b-seite** [comment]
Hi @Camille92,

that was the thing i forgot to write: It calculates a value from 1 to 0 depending on the TBP. 
1 means TBP is 50% and 0 means TBP is 0% or 100%. Then it calculates the difference between PDiv and pDivMin. And this Difference is multiplied with the value above.
So, that means if you have set mode to linear, pdiv = 40% and pDivMin = 10% then:
TBP = 50% -> pDiv is 40%
TBP = 0 % -> pDiv is 10%
TBP = 25% -> pDiv is 10% + 0,5 * 40%-10% = 25%
Hope that helps to understand what that code does.

I think that it could be helpful i. e. to automatically stop trading if TBP is on its limits by setting pDivMin to 0. 

But if you don't agree that i´s useful we do not need to implement it

**Comment by Camille92** [comment]
That's great :)

**Comment by ctubio** [comment]
ima leave this here as a reminder to myself https://www.gnu.org/software/libc/manual/html_node/Mathematical-Constants.html

**Comment by ctubio** [comment]
awesome'¡ soo even if is slighly diff ima mark as done the mini task at #6 hope you agree :dancer:

**Comment by b-seite** [comment]
Hey Carles, 
thanks for merging 😄
I still have one small issue with that and did not find a solution: In the GUI the pDiff is not showing up on website opening. it will be visible when the first TBP update is triggered. 
Can you help with that?
Thanks Boris

**Comment by ctubio** [comment]
sure lets open a miniissue for it so we dont forget (will do asap)

**Comment by ctubio** [comment]
hope pDiv is now OK at https://github.com/ctubio/Krypto-trading-bot/commit/5114a89eef5367f6c6d3314a91e15f2b42736dac

**Pull request merged**
